### PR TITLE
fix openapi item with url illegalKey 400 error

### LINKED ISSUE #4447: openapi请求如果key是a.bS/TT/AT，则报404错误
openapi的Java client，1.7.0，如果key是a.bS/TT/AT，则请求就会报404错误。上次修完后，[]是可以了，但是key为a.bS/TT/AT还是不行，只不过这次报404了

### PR DESCRIPTION
**Pull request by AbnerHuang2**
## What's the purpose of this PR

fix openapi item with url illegalKey 400 error

## Which issue(s) this PR fixes:
Fixes #4447 

## Brief changelog

get/update/delete the item key with / \ or start with .  will encode key by encodeItems API, otherwise, it will act like old way.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

File: apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java [hunk 1]
```diff
@@ -33,22 +33,13 @@
 import com.ctrip.framework.apollo.common.utils.BeanUtils;
 import com.ctrip.framework.apollo.core.utils.StringUtils;
 
-import java.util.Collection;
-import java.util.Collections;
-import java.util.List;
-import java.util.Objects;
+import java.nio.charset.StandardCharsets;
+import java.util.*;
```
Comment (mghio) [inline apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java:37]: I think use Single-Type-Import (e.g., import java.util.List) increases the readability of the program and it will be very clear which classes have been used. 

BTW, in compile time, the import java.util.* will search for whole package to find the correct class' information.

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java [hunk 2]
```diff
@@ -84,7 +84,13 @@ public OpenApiPathBuilder namespacesPathVal(String namespaces) {
   }
 
   public OpenApiPathBuilder itemsPathVal(String items) {
-    pathVariable.put(ITEMS_PATH, escapePath(items));
+    if(UrlUtils.hasIllegalChar(items)){
+      items = new String(Base64.getUrlEncoder().encode(items.getBytes(StandardCharsets.UTF_8)));
```
Comment (mghio) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:88]: How about extracting this duplication of `Base64.getUrlEncoder().encode(items.getBytes(StandardCharsets.UTF_8))` into UrlUtils?

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java [hunk 3]
```diff
@@ -84,7 +84,13 @@ public OpenApiPathBuilder namespacesPathVal(String namespaces) {
   }
 
   public OpenApiPathBuilder itemsPathVal(String items) {
-    pathVariable.put(ITEMS_PATH, escapePath(items));
+    if(UrlUtils.hasIllegalChar(items)){
```
Comment (mghio) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:87]:
```suggestion
    if (UrlUtils.hasIllegalChar(items)) {
```

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java [hunk 4]
```diff
@@ -84,7 +84,13 @@ public OpenApiPathBuilder namespacesPathVal(String namespaces) {
...
+      items = new String(Base64.getUrlEncoder().encode(items.getBytes(StandardCharsets.UTF_8)));
+      pathVariable.put(ENCODE_ITEMS_PATH, items);
+    }else{
```
Comment (mghio) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:90]:
```suggestion
    } else {
```

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+import com.google.common.base.Strings;
+
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * @author Abner
+ * @since  8/31/22
+ */
+public class UrlUtils {
```
Comment (mghio) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java:28]: How about using final class?

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java [hunk 6]
```diff
@@ -169,6 +170,9 @@ public List<ItemDTO> findDeletedItems(String appId, Env env, String clusterName,
   }
 
   public ItemDTO loadItem(Env env, String appId, String clusterName, String namespaceName, String key) {
+    if(UrlUtils.hasIllegalChar(key)){
```
Comment (mghio) [inline apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java:173]:
```suggestion
    if (UrlUtils.hasIllegalChar(key)) {
```

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java [hunk 7]
```diff
@@ -67,6 +69,13 @@ public OpenItemDTO getItem(@PathVariable String appId, @PathVariable String env,
     return this.itemOpenApiService.getItem(appId, env, clusterName, namespaceName, key);
   }
 
+  @GetMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodeItems/{key:.+}")
+  public OpenItemDTO getItemByEncodeKey(@PathVariable String appId, @PathVariable String env, @PathVariable String clusterName,
+                             @PathVariable String namespaceName, @PathVariable String key) {
+    key = new String(Base64.getUrlDecoder().decode(key.getBytes(StandardCharsets.UTF_8)));
```
Comment (mghio) [inline apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java:75]: How about extracting this duplication of `new String(Base64.getUrlDecoder().decode(key.getBytes(StandardCharsets.UTF_8)))` into UrlUtils?

File: apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java (hunk 1 above)
Comment (AbnerHuang2) [reply apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java:37]: ok. my idea transfer import * when importing more than 5 classes in one package ,  I'll increase it.

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java (hunk 7 above)
Comment (AbnerHuang2) [reply apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java:75]: that's a good idea.

File: apollo-openapi/pom.xml [hunk 8]
```diff
@@ -37,6 +37,10 @@
       <groupId>com.ctrip.framework.apollo</groupId>
       <artifactId>apollo-core</artifactId>
     </dependency>
+    <dependency>
```
Comment (nobodyiam) [inline apollo-openapi/pom.xml:40]: apollo-common has many dependencies, it's not friendly for those apps that depend on apollo-openapi.
I think it's ok to have some duplications as the logic of UrlUtils is simple and clear.

File: apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java [hunk 9]
```diff
@@ -238,6 +230,13 @@ public ItemDTO get(@PathVariable("appId") String appId,
     return BeanUtils.transform(ItemDTO.class, item);
   }
 
+  @GetMapping("/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodeItems/{key:.+}")
```
Comment (nobodyiam) [inline apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java:233]:
```suggestion
  @GetMapping("/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodedItems/{key:.+}")
```

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java [hunk 10]
```diff
@@ -34,11 +35,12 @@ public class OpenApiPathBuilder {
   private static final String CLUSTERS_PATH = "clusters";
   private static final String NAMESPACES_PATH = "namespaces";
   private static final String ITEMS_PATH = "items";
+  private static final String ENCODE_ITEMS_PATH = "encodeItems";
```
Comment (nobodyiam) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:38]:
```suggestion
  private static final String ENCODED_ITEMS_PATH = "encodedItems";
```

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java [hunk 11]
```diff
@@ -84,7 +86,12 @@ public OpenApiPathBuilder namespacesPathVal(String namespaces) {
   }
 
   public OpenApiPathBuilder itemsPathVal(String items) {
-    pathVariable.put(ITEMS_PATH, escapePath(items));
+    if (UrlUtils.hasIllegalChar(items)) {
+      pathVariable.put(ENCODE_ITEMS_PATH, UrlUtils.encode(items));
```
Comment (nobodyiam) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:90]: Is it necessary to use `escapePath` for the base64 encoded string?

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClientTest.java [hunk 12]
```diff
@@ -32,6 +34,71 @@ public void testCreate() {
...
+
+    ApolloOpenApiClient client = ApolloOpenApiClient.newBuilder().withPortalUrl(someUrl).withToken(someToken).build();
+
+    OpenItemDTO createItem = new OpenItemDTO();
+    createItem.setKey(key);
+    createItem.setValue(value);
+
+    createItem.setDataChangeCreatedBy(operator);
+    OpenItemDTO item1 = client.createItem(appId, env, cluster, namespace, createItem);
+    System.out.println("create item : "+item1);
```
Comment (nobodyiam) [inline apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClientTest.java:76]: It's not a good practice to use the System.out in unit test as it's not testable.
Instead, we could use mockito and junit to verify the logic.
BTW, it's better to verify the item logic in `ItemOpenApiServiceTest`.

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java [hunk 13]
```diff
@@ -67,6 +68,12 @@ public OpenItemDTO getItem(@PathVariable String appId, @PathVariable String env,
     return this.itemOpenApiService.getItem(appId, env, clusterName, namespaceName, key);
   }
 
+  @GetMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodeItems/{key:.+}")
```
Comment (nobodyiam) [inline apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java:71]:
```suggestion
  @GetMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodedItems/{key:.+}")
```

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java [hunk 14]
```diff
@@ -118,6 +125,15 @@ public void updateItem(@PathVariable String appId, @PathVariable String env,
     }
   }
 
+  @PreAuthorize(value = "@consumerPermissionValidator.hasModifyNamespacePermission(#request, #appId, #namespaceName, #env)")
+  @PutMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodeItems/{key:.+}")
```
Comment (nobodyiam) [inline apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java:129]:
```suggestion
  @PutMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodedItems/{key:.+}")
```

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java [hunk 15]
```diff
@@ -137,6 +153,15 @@ public void deleteItem(@PathVariable String appId, @PathVariable String env,
     this.itemOpenApiService.removeItem(appId, env, clusterName, namespaceName, key, operator);
   }
 
+  @PreAuthorize(value = "@consumerPermissionValidator.hasModifyNamespacePermission(#request, #appId, #namespaceName, #env)")
+  @DeleteMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/encodeItems/{key:.+}")
+  public void deleteItemByEncodeKey(@PathVariable String appId, @PathVariable String env,
+                         @PathVariable String clusterName, @PathVariable String namespaceName,
+                         @PathVariable String key, @RequestParam String operator,
+                         HttpServletRequest request) {
+    this.deleteItem(appId,env,clusterName,namespaceName,UrlUtils.decode(key),operator,request);
```
Comment (nobodyiam) [inline apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java:162]: Please use the [apollo code style](https://github.com/apolloconfig/apollo/tree/master/apollo-buildtools/style) for format the codes.
```suggestion
    this.deleteItem(appId, env, clusterName, namespaceName, UrlUtils.decode(key), operator, request);
```

**Review by nobodyiam — CHANGES_REQUESTED** [review]

File: apollo-openapi/pom.xml (hunk 8 above)
Comment (AbnerHuang2) [reply apollo-openapi/pom.xml:40]: I thought so. but when I extract encode/decode method in UrlUtils, It will use in adminservice/ItemController. but adminservice don't have dependency of openapi,  as the definition of common, maybe is more fit for the position of UrlUtils. so, if I just define UrlUtils in openapi, how should I decode key in adminservice/ItemController?  duplicate the decode method in UrlUtils?  it may not a good maintenance.

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClientTest.java (hunk 12 above)
Comment (AbnerHuang2) [reply apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClientTest.java:76]: OK， System.out is just for output, I'll remove them and  transfer the item vferify logic in ItemOpenApiServiceTest.

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java (hunk 11 above)
Comment (AbnerHuang2) [reply apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:90]: it's necessary. 
1. for example, if the item key is Chinese character or other special character(except /  \ .).  use escapePath may more suitable.
2. when openapi client is in high level, but portal is in low level. it can also work fine.

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java [hunk 16]
```diff
@@ -0,0 +1,52 @@
...
+import java.util.Base64;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * @author Abner
+ * @since  8/31/22
+ */
+public final class UrlUtils {
+    private static final String ILLEGAL_KEY_REGEX = "[/\\\\]+|^\\.";
```
Comment (nobodyiam) [inline apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:31]: This regex is complex, does it simply match '/' and '\'?

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java [hunk 17]
```diff
@@ -0,0 +1,52 @@
...
+
+    private UrlUtils() {}
+
+    public static boolean hasIllegalChar(String key) {
```
Comment (nobodyiam) [inline apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:35]: This logic is reused in apollo-openapi and apollo-portal, as apollo-portal depends on apollo-openapi, I think we could put this into apollo-openapi.

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java [hunk 18]
```diff
@@ -0,0 +1,52 @@
...
+        return matcher.find();
+    }
+
+    public static String encode(String key){
+        return new String(Base64.getEncoder().encode(key.getBytes(StandardCharsets.UTF_8)));
+    }
+
+    public static String decode(String key){
+        return new String(Base64.getDecoder().decode(key.getBytes(StandardCharsets.UTF_8)));
+    }
```
Comment (nobodyiam) [inline apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:50]: These are simply base64 encode and decode logic. I don't think it's necessary to have a common util for them.

**Review by nobodyiam — CHANGES_REQUESTED** [review]

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java (hunk 16 above)
Comment (AbnerHuang2) [reply apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:31]: but '\' and single '.'  is also need to encode, otherwise, it will also encounter 400 error.

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java (hunk 18 above)
Comment (AbnerHuang2) [reply apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:50]: but if we change another algorithm, it should modify in many position, it's easily forgotten in somewhere.

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java (hunk 16 above)
Comment (AbnerHuang2) [reply apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:31]: but '\\' and single '.' is also need to encode, otherwise, it will also encounter 400 error.

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java [hunk 19]
```diff
@@ -0,0 +1,52 @@
...
+public final class UrlUtils {
+    private static final String ILLEGAL_KEY_REGEX = "[/\\\\]+|^\\.";
+
+    private UrlUtils() {}
+
+    public static boolean hasIllegalChar(String key) {
+        if(Strings.isNullOrEmpty(key)){
+            return false;
+        }
+        final Pattern pattern = Pattern.compile(ILLEGAL_KEY_REGEX, Pattern.MULTILINE);
```
[the remark this answers is not in the document]
Comment (AbnerHuang2) [reply apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/UrlUtils.java:39]: yeah, nice suggestion!

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java [hunk 20]
```diff
@@ -0,0 +1,43 @@
...
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * @author Abner
+ * @since  8/31/22
+ */
+public final class UrlUtils {
+
+    private static final String ILLEGAL_KEY_REGEX = "[/\\\\]+|^\\.";
```
Comment (nobodyiam) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java:29]: I think only keys containing `/` and `\` need to be encoded. I tested the key `<>[]^`{|}.` which worked well.

Comment (AbnerHuang2) [reply apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java:29]: 企业微信截图_59e427c3-9cc8-4ee7-a96c-64772ab90852

image

if using '.' , status is 200, but get a response in HTML, not JSON.

Comment (AbnerHuang2) [reply apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java:29]: image

but '.a'  works fine, I can change the regex with "[/\\\\]+|^.$"

Comment (nobodyiam) [reply apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java:29]: The `.` is a meaningless key, I think we don't need to support it.

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java [hunk 21]
```diff
@@ -84,7 +89,12 @@ public OpenApiPathBuilder namespacesPathVal(String namespaces) {
   }
 
   public OpenApiPathBuilder itemsPathVal(String items) {
-    pathVariable.put(ITEMS_PATH, escapePath(items));
+    if (UrlUtils.hasIllegalChar(items)) {
+      pathVariable.put(ENCODED_ITEMS_PATH,
+          new String(Base64.getEncoder().encode(items.getBytes(StandardCharsets.UTF_8))));
+    } else {
+      pathVariable.put(ITEMS_PATH, escapePath(items));
+    }
```
Comment (nobodyiam) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/url/OpenApiPathBuilder.java:97]: How about this?
```suggestion
    if (UrlUtils.hasIllegalChar(items)) {
      items = new String(Base64.getEncoder().encode(items.getBytes(StandardCharsets.UTF_8))));
    }
    pathVariable.put(ITEMS_PATH, escapePath(items));
```

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java [hunk 22]
```diff
@@ -75,6 +76,26 @@ public void testGetItem() throws Exception {
             someAppId, someCluster, someNamespace, someKey), get.getURI().toString());
   }
 
+  @Test
+  public void testGetItemByIllegalKey() throws Exception {
+    String someKey = "/";
```
Comment (nobodyiam) [inline apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java:81]: It's better to use a more meaningful key, e.g.
```suggestion
    String someKey = "a/b";
```

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java [hunk 23]
```diff
@@ -153,6 +174,33 @@ public void testUpdateItem() throws Exception {
             someNamespace, someKey), put.getURI().toString());
   }
 
+  @Test
+  public void testUpdateItemByIllegalKey() throws Exception {
+    String someKey = "\\";
```
Comment (nobodyiam) [inline apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java:179]: The same as above.

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java [hunk 24]
```diff
@@ -227,6 +275,27 @@ public void testRemoveItem() throws Exception {
             someAppId, someCluster, someNamespace, someKey, someOperator), delete.getURI().toString());
   }
 
+  @Test
+  public void testRemoveItemByIllegalKey() throws Exception {
+    String someKey = ".";
```
Comment (nobodyiam) [inline apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java:280]: The same as above.

File: apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java [hunk 25]
```diff
@@ -169,6 +170,9 @@ public List<ItemDTO> findDeletedItems(String appId, Env env, String clusterName,
   }
 
   public ItemDTO loadItem(Env env, String appId, String clusterName, String namespaceName, String key) {
+    if (UrlUtils.hasIllegalChar(key)) {
+      return itemAPI.loadItemByEncodeKey(env,appId,clusterName,namespaceName,key);
```
Comment (nobodyiam) [inline apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java:174]: please format the code.

File: apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java [hunk 26]
```diff
@@ -0,0 +1,43 @@
...
+
+import com.google.common.base.Strings;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * @author Abner
+ * @since  8/31/22
+ */
+public final class UrlUtils {
```
Comment (nobodyiam) [inline apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/utils/UrlUtils.java:27]: We need to provide a unit test for UrlUtils.

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java (hunk 22 above)
Comment (AbnerHuang2) [reply apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/service/ItemOpenApiServiceTest.java]: ok.

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/utils/UrlUtilsTest.java [hunk 27]
```diff
@@ -0,0 +1,43 @@
...
+import org.junit.Test;
+
+/**
+ * @author huanghousheng
+ * @since 9/7/22
+ */
+public class UrlUtilsTest {
+
+  @Test
+  public void testHasIllegalChar() {
```
Comment (nobodyiam) [inline apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/utils/UrlUtilsTest.java:32]: The test needs to also cover the `\` case.

File: apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/utils/UrlUtilsTest.java [hunk 28]
```diff
@@ -0,0 +1,43 @@
...
+    String someKey = "protocol//:host:port";
+    assertTrue(UrlUtils.hasIllegalChar(someKey));
+  }
+
+  @Test
+  public void testNotHasIllegalChar() {
```
Comment (nobodyiam) [inline apollo-openapi/src/test/java/com/ctrip/framework/apollo/openapi/client/utils/UrlUtilsTest.java:38]: It's better to cover other normal case like `a.b`.

**Review by nobodyiam — APPROVED** [review]
LGTM
