### PR TITLE
Fix the NPE occurred when using EnableApolloConfig with Spring 3.1.1

### LINKED ISSUE #4178: NPE occurred when using EnableApolloConfig with Spring 3.1.1
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
When using `@EnableApolloConfig` with Spring 3.1.1, NullPointerException will occur.

**To Reproduce**
1. Mark a configuration class with `@EnableApolloConfig`
```java
@Configuration
@EnableApolloConfig(value = "application", order = 10)
public class AppConfig {
  @Bean
  public NormalBean normalBean(@Value("${batch:100}") int batch) {
    NormalBean bean = new NormalBean();
    bean.setBatch(batch);
    return bean;
  }
}
```

2. Run the application with Spring version 3.1.1
3. NullPointerException will occur
```
Exception in thread "main" java.lang.NullPointerException
	at com.ctrip.framework.apollo.spring.spi.DefaultApolloConfigRegistrarHelper.resolveNamespaces(DefaultApolloConfigRegistrarHelper.java:52)
	at com.ctrip.framework.apollo.spring.spi.DefaultApolloConfigRegistrarHelper.registerBeanDefinitions(DefaultApolloConfigRegistrarHelper.java:29)
	at com.ctrip.framework.apollo.spring.annotation.ApolloConfigRegistrar.registerBeanDefinitions(ApolloConfigRegistrar.java:20)
	at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:331)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:228)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:149)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:126)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:263)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:203)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:617)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:446)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at com.ctrip.framework.apollo.demo.spring.AnnotationApplication.main(AnnotationApplication.java:12)
```
4. 

**Expected behavior**
The application should work well

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

### PR DESCRIPTION
**Pull request by nobodyiam**
## What's the purpose of this PR

Fix the NPE occurred when using EnableApolloConfig with Spring 3.1.1

## Which issue(s) this PR fixes:
Fixes #4178

## Brief changelog

* Disable namespace placeholder support for Spring version prior to 3.2.x

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

File: apollo-client/src/main/java/com/ctrip/framework/apollo/spring/spi/DefaultApolloConfigRegistrarHelper.java [hunk 1]
```diff
@@ -62,6 +62,10 @@ public void registerBeanDefinitions(AnnotationMetadata importingClassMetadata, B
   }
 
   private String[] resolveNamespaces(String[] namespaces) {
+    // no support for Spring version prior to 3.2.x, see https://github.com/apolloconfig/apollo/issues/4178
+    if (this.environment == null) {
+      return namespaces;
```
Comment (Anilople) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/spring/spi/DefaultApolloConfigRegistrarHelper.java:67]: Before return namespaces, can we use log to warn the user?
```suggestion
      logger.warn("no support for Spring version prior to 3.2.x, if you want use placehoders in the value of @EnableApolloConfig, please upgrade Spring's version to at least 3.3.x or higer version. see https://github.com/apolloconfig/apollo/issues/4178 for more detail");
      return namespaces;
```

Comment (Anilople) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/spring/spi/DefaultApolloConfigRegistrarHelper.java:67]: Or some user not use placeholder, but they use spring version prior to 3.2.x, we can detect the '$', then log a warning.

```suggestion
      if ( namespaces contains '$') {
            logger.warn("xxxxx")
      }
      return namespaces;
```

Comment (nobodyiam) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/spring/spi/DefaultApolloConfigRegistrarHelper.java:72]: Sounds a good idea.

**Review by Anilople — APPROVED** [review]
LGTM
