### PR TITLE
fix create namespace with single dot 500 error

### LINKED ISSUE #4565: create namespace with single dot 500 error
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
create namespace with . will crash in query namespace.

**To Reproduce**
1.  create namespace with single dot(.)
2. refresh namespace. 

**Expected behavior**
display normally.

**Screenshots**

https://user-images.githubusercontent.com/50099513/189686696-179451cc-00b9-433b-a2ef-f270baf848c2.mov

### Additional Details & Logs

- Latest Version (All)

### PR DESCRIPTION
**Pull request by AbnerHuang2**
## What's the purpose of this PR

fix create namespace with single dot 500 error

## Which issue(s) this PR fixes:
Fixes #4565 

## Brief changelog

fix create namespace with single dot 500 error

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

File: apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/InputValidator.java [hunk 1]
```diff
@@ -24,9 +24,9 @@
  * @author Jason Song(song_s@ctrip.com)
  */
 public class InputValidator {
-  public static final String INVALID_CLUSTER_NAMESPACE_MESSAGE = "Only digits, alphabets and symbol - _ . are allowed";
+  public static final String INVALID_CLUSTER_NAMESPACE_MESSAGE = "Only digits, alphabets and symbol - _ . (except single .) are allowed";
   public static final String INVALID_NAMESPACE_NAMESPACE_MESSAGE = "not allowed to end with .json, .yml, .yaml, .xml, .properties";
-  public static final String CLUSTER_NAMESPACE_VALIDATOR = "[0-9a-zA-Z_.-]+";
+  public static final String CLUSTER_NAMESPACE_VALIDATOR = "[0-9a-zA-Z-]+[0-9a-zA-Z._-]*";
```
Comment (mghio) [inline apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/InputValidator.java:29]: Please add some unit test in [InputValidatorTest](https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/test/java/com/ctrip/framework/apollo/common/utils/InputValidatorTest.java).

**Comment by AbnerHuang2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by nobodyiam — APPROVED** [review]
LGTM
